# Generated by Django 5.2.5 on 2025-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuterecord',
            name='mode_of_transport',
            field=models.CharField(choices=[('car_petrol', 'Car (Petrol)'), ('car_diesel', 'Car (Diesel)'), ('car_hybrid', 'Car (Hybrid)'), ('car_electric', 'Car (Electric)'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('train', 'Train'), ('bicycle', 'Bicycle'), ('walking', 'Walking'), ('taxi', 'Taxi'), ('auto_rickshaw', 'Auto Rickshaw'), ('metro', 'Metro/Subway')], max_length=50),
        ),
    ]
