# Generated by Django 5.2.5 on 2025-08-29 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_commuterecord_mode_of_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuterecord',
            name='distance',
            field=models.FloatField(help_text='Distance traveled in kilometers'),
        ),
        migrations.AlterField(
            model_name='commuterecord',
            name='fuel_efficiency',
            field=models.FloatField(help_text='Mileage in km/L (kilometers per liter)'),
        ),
        migrations.AlterField(
            model_name='commuterecord',
            name='predicted_emission',
            field=models.FloatField(help_text='Predicted CO2 emission in kg'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_co2_goal', models.FloatField(default=100.0, help_text='Monthly CO₂ emission goal in kg')),
                ('preferred_transport', models.CharField(blank=True, help_text='Preferred eco-friendly transport', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
