# Generated by Django 5.2.5 on 2025-09-02 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_monthlysummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commuterecord',
            name='road_type',
            field=models.CharField(choices=[('city', 'City'), ('highway', 'Highway')], default='city', max_length=20),
        ),
        migrations.AddField(
            model_name='commuterecord',
            name='traffic_intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='commuterecord',
            name='weather',
            field=models.CharField(choices=[('clear', 'Clear'), ('rainy', 'Rainy'), ('snowy', 'Snowy')], default='clear', max_length=20),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('eco_warrior', 'Eco Warrior 🌱')], max_length=50)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
